### ISSUE TITLE
Faster motors

### ISSUE THREAD

**Issue by hyansuper** [hyansuper/rcute-cozmars-server#10]

**Comment by anjok** [comment]
What does that mean? Faster servos or faster N20s?

**Comment by hyansuper** [comment]
May be we could try faster n20 motors. But battery is only 3.7v ，faster motors are less powerful

**Comment by anjok** [comment]
Add a power converter and use 7.4v?

**Comment by anjok** [comment]
How fast are the servos anyway? The actual Cozmo is pretty darn fast... would it be enough to play these reaction games with mg90 or Sg90?

**Comment by anjok** [comment]
And could you open source the cad model files too? I want to add touch, gyro and one/two more led sensors, in addition to the 2 now.

**Comment by hyansuper** [comment]
Hi, @anjok , your ideas are feasible. problem is there is very limited room left for other components

I personally don't like a voltage convertor, it adds system complexity.

there is space for another 2 ir sensors at bottom rear, maybe you want to install ir sensors at front and rear to detect cliff and stop the robot on edge of table? but unlike cozmo, when cozmars falls off table, it's certain to break. so the best policy is not to play "stop at cliff" game.

For gyro sensors, do you have any particular application in mind?  since the robot has no feed back on N20 motors to tell how far it's travelled, I just gave up on enabling the robot the ability to navigate

**Comment by anjok** [comment]
The gyros would be for the kids picking it up. Then it would notice and either purr or throw a fit. 

As for the size... it's not really written in stone. That's why I'd like the actual CAD files. 

By the way couldn't we use sg90 servos for driving? I saw a video where someone clipped something and added an output line.

**Comment by anjok** [comment]
https://electronics.stackexchange.com/questions/258323/towerpro-sg90-servo-motor-adding-analog-feedback

**Comment by anjok** [comment]
@hyansuper i don't know if they can actually spinnlike normal motors though

**Comment by anjok** [comment]
From the comments apparently it can. And it would remove the need for the motor controller...

**Comment by hyansuper** [comment]
Why not many online shop selling these! they are useful! although we don't know how well they perform.

and, sorry to disappoint you that CAD files won't be public :(

**Comment by hyansuper** [comment]
> The gyros would be for the kids picking it up. Then it would notice and either purr or throw a fit. 

Pick up detection can be achieved by ir sensor，I think that's how cozmo do it

**Comment by hyansuper** [comment]
I will use 20r/m motors in next version. it's unnoticeably faster. I am conservative about faster motors because of 3.7v battery
